name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Cambia si tu rama principal es otra

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: tu_usuario/tu_repositorio:latest
